### ISSUE TITLE
Triggering animations kick me from server

### ISSUE THREAD

**Issue by Abimander** [ZsoltMolnarrr/BetterCombat#113]
**Minecraft version** - 1.19
**Mod loader** - Fabric
**Mod version** - 1.4.1
**I am using the latest version available** - Yes

**Describe the bug**
I wanted to add Better Combat to my server. Everything was okay when I tested it in Singleplayer to make sure it was compatible with my other mods, and it worked great. I added it to the server, and things broke. Whenever I went to attack, it would trigger the animation, and it would kick me from the server
(Note: I was testing it with a weapon from MC Dungeons Weapons, and a plain diamond axe}. 
There's the likely possibility that its a conflict issue between BC, and a mod that's on the server, but I dug deep into logs, and files, and I couldn't find anything that said so.

**To Reproduce**
1. Add the mod, and its dependency to a Server 
2. Attack with a weapon
3. The server will kick you back to the multiplayer screen, but nothing crashes

**Expected behavior**
I expected the animation to play, and the mod work smoothly

**Screenshots or video recordings**
Copy/Pasted text from a log. This is the only thing I could track down that could be the problem.
```
java.lang.NoSuchMethodError: 'float java.util.Random.nextFloat(float, float)'
        at net.bettercombat.utils.SoundHelper.playSound(SoundHelper.java:29)
        at net.bettercombat.network.ServerNetwork.lambda$initializeHandlers$5(ServerNetwork.java:113)
        at net.minecraft.class_3738.run(class_3738.java:18)
        at net.minecraft.class_1255.method_18859(class_1255.java:157)
        at net.minecraft.class_4093.method_18859(class_4093.java:23)
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:160)
        at net.minecraft.class_1255.method_16075(class_1255.java:131)
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
        at net.minecraft.class_1255.method_18857(class_1255.java:140)
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Additional context**
The only other thing I find interesting is that I can see the animation play clearly for a second before the server kicks me. I hope this can narrow down whatever might be causing it. If you can't reproduce, and solve the bug I can't ask for anything else. Thank you.

**Comment by ZsoltMolnarrr** [comment]
Hello!
Please provide the full crashlog, without that I can barely do anything.

**Comment by ZsoltMolnarrr** [comment]
The issue is definitely related to your installation.
It is missing a function from `java.util`, which means you most likely use an outdated java installation.
This mod requires Java 17 JVM.
Suggested download source: https://www.oracle.com/java/technologies/downloads/
