### ISSUE TITLE
[Forge 1.19-41.0.38] Error Code: -1

### ISSUE THREAD

**Issue by sort50** [ZsoltMolnarrr/BetterCombat#115]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 9/25/22, 1:26 PM
Description: Rendering overlay

java.lang.NullPointerException: Registry Object not present: minecraft:empty
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19-41.0.38-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.getVanillaFluidType(ForgeHooks.java:816) ~[forge-1.19-41.0.38-universal.jar%2396!/:?] {re:classloading}
	at net.minecraft.world.level.material.Fluid.getFluidType(Fluid.java:108) ~[client-1.19-20220607.102129-srg.jar%2391!/:?] {re:classloading}
	at net.minecraftforge.client.RenderProperties.get(RenderProperties.java:57) ~[forge-1.19-41.0.38-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.getFluidMaterials(ForgeHooksClient.java:482) ~[forge-1.19-41.0.38-universal.jar%2396!/:?] {re:classloading}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:computing_frames,re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.gatherFluidTextures(ForgeHooksClient.java:477) ~[forge-1.19-41.0.38-universal.jar%2396!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.optifine.reflect.Reflector.call(Reflector.java:847) ~[OptiFine_1.19_HD_U_H8.jar%2397!/:?] {re:classloading}
	at net.minecraft.client.resources.model.ModelBakery.processLoading(ModelBakery.java:245) ~[client-1.19-20220607.102129-srg.jar%2391!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraftforge.client.model.ForgeModelBakery.<init>(ForgeModelBakery.java:60) ~[forge-1.19-41.0.38-universal.jar%2396!/:?] {re:classloading}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:57) ~[client-1.19-20220607.102129-srg.jar%2391!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.19-20220607.102129-srg.jar%2391!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19-20220607.102129-srg.jar%2391!/:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19-41.0.38-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.getVanillaFluidType(ForgeHooks.java:816) ~[forge-1.19-41.0.38-universal.jar%2396!/:?] {re:classloading}
	at net.minecraft.world.level.material.Fluid.getFluidType(Fluid.java:108) ~[client-1.19-20220607.102129-srg.jar%2391!/:?] {re:classloading}
	at net.minecraftforge.client.RenderProperties.get(RenderProperties.java:57) ~[forge-1.19-41.0.38-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.getFluidMaterials(ForgeHooksClient.java:482) ~[forge-1.19-41.0.38-universal.jar%2396!/:?] {re:classloading}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:computing_frames,re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.gatherFluidTextures(ForgeHooksClient.java:477) ~[forge-1.19-41.0.38-universal.jar%2396!/:?] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1291) ~[client-1.19-20220607.102129-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1070) ~[client-1.19-20220607.102129-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.19-20220607.102129-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%2391!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.38.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, VanillaTweaks_r541098.zip, 3.0.3v_VisualEnchantments (1).zip
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.NullPointerException: Registry Object not present: minecraft:empty
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Registry Object not present: minecraft:empty
	at java.base/java.util.Objects.requireNonNull(Objects.java:334)
	at TRANSFORMER/forge@41.0.38/net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204)
	at TRANSFORMER/forge@41.0.38/net.minecraftforge.common.ForgeHooks.getVanillaFluidType(ForgeHooks.java:816)
	at TRANSFORMER/minecraft@1.19/net.minecraft.world.level.material.Fluid.getFluidType(Fluid.java:108)
	at TRANSFORMER/forge@41.0.38/net.minecraftforge.client.RenderProperties.get(RenderProperties.java:57)
	at TRANSFORMER/forge@41.0.38/net.minecraftforge.client.ForgeHooksClient.getFluidMaterials(ForgeHooksClient.java:482)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at TRANSFORMER/forge@41.0.38/net.minecraftforge.client.ForgeHooksClient.gatherFluidTextures(ForgeHooksClient.java:477)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at TRANSFORMER/net.optifine/net.optifine.reflect.Reflector.call(Reflector.java:847)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.resources.model.ModelBakery.processLoading(ModelBakery.java:245)
	at TRANSFORMER/forge@41.0.38/net.minecraftforge.client.model.ForgeModelBakery.<init>(ForgeModelBakery.java:60)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:57)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 418886840 bytes (399 MiB) / 1174405120 bytes (1120 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f91
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Graphics card #1 name: AMD Radeon(TM) RX Vega 10 Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x15d8
	Graphics card #1 versionInfo: DriverVersion=27.20.22025.2003
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 19141.43
	Virtual memory used (MB): 14637.20
	Swap memory total (MB): 4872.12
	Swap memory used (MB): 281.71
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19-forge-41.0.38
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon(TM) RX Vega 10 Graphics  GL version 3.2.14742 Core Profile Forward-Compatible Context 21.20.25.02 27.20.22025.2003, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx 
	OptiFine Version: OptiFine_1.19_HD_U_H8
	OptiFine Build: 20220709-163719
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.14742 Core Profile Forward-Compatible Context 21.20.25.02 27.20.22025.2003
	OpenGlRenderer: AMD Radeon(TM) RX Vega 10 Graphics 
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8
	ModLauncher: 10.0.1+10.0.1+main.e9521dc3
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		vanillaplustools-1.19-1.0.jar                     |Vanilla+ Tools                |vanillaplustools              |1.19-1.0            |COMMON_SET|Manifest: NOSIGNATURE
		upgradednetherite_items-1.19-4.0.0.1-beta.jar     |Upgraded Netherite : Items    |upgradednetherite_items       |1.19-4.0.0.1-beta   |COMMON_SET|Manifest: NOSIGNATURE
		farmingforblockheads-forge-1.19-11.0.0.jar        |Farming for Blockheads        |farmingforblockheads          |11.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-1.19-1.5.0.jar                     |Guard Villagers               |guardvillagers                |1.4.2               |COMMON_SET|Manifest: NOSIGNATURE
		upgradedcore-1.19-4.0.0.2-beta.jar                |Upgraded Core                 |upgradedcore                  |1.19-4.0.0.2-beta   |COMMON_SET|Manifest: NOSIGNATURE
		cfm-7.0.0-pre30-1.19.jar                          |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre30         |COMMON_SET|Manifest: NOSIGNATURE
		player-animation-lib-forge-0.3.5.jar              |Player Animator               |playeranimator                |0.3.5               |COMMON_SET|Manifest: NOSIGNATURE
		upgradednetherite_ultimate-1.19-4.0.0.1-beta.jar  |Upgraded Netherite : Ultimerit|upgradednetherite_ultimate    |1.19-4.0.0.1-beta   |COMMON_SET|Manifest: NOSIGNATURE
		balm-4.0.0+0.jar                                  |Balm                          |balm                          |4.0.0+0             |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-7.0.72-forge.jar                     |Cloth Config v4 API           |cloth_config                  |7.0.72              |COMMON_SET|Manifest: NOSIGNATURE
		bettercombat-forge-1.4.0+1.19.jar                 |Better Combat                 |bettercombat                  |1.4.0+1.19          |ERROR     |Manifest: NOSIGNATURE
		forge-1.19-41.0.38-universal.jar                  |Forge                         |forge                         |41.0.38             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		revampedwolf-1.19-2.0.0.jar                       |RevampedWolf                  |revampedwolf                  |1.19-2.0.0          |COMMON_SET|Manifest: NOSIGNATURE
		upgradednetherite-1.19-5.0.0.3-beta.jar           |Upgraded Netherite            |upgradednetherite             |1.19-5.0.0.3-beta   |COMMON_SET|Manifest: NOSIGNATURE
		gravelminer-forge-1.19-13.0.0.jar                 |GravelMiner                   |gravelminer                   |13.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.19-5.8.5rc1-forge.jar                |Journeymap                    |journeymap                    |5.8.5rc1            |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 11509e40-54df-4796-b2cc-e046b0696920
	FML: 41.0
	Forge: net.minecraftforge:41.0.38

**Comment by ZsoltMolnarrr** [comment]
Failing to use issue form.
Partial crashlog.
No better combat related information.
