### ISSUE TITLE
Weapon Leveling mod

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [ZsoltMolnarrr/BetterCombat#124]
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - any
**I am using the latest version available** - 1.4.3

**Describe the bug**
Launch crash, mixin conflict.

**To Reproduce**
1. Load the game

```
Caused by: java.lang.UnsupportedOperationException: Redirector target failure for bettercombat.mixins.json:PlayerEntityMixin->@Redirect::setStackInHand_Redirect(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/InteractionHand;Lnet/minecraft/world/item/ItemStack;)V
    at org.spongepowered.asm.mixin.injection.invoke.RedirectInjector.inject(RedirectInjector.java:320) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
    at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
    at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1355) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]

```

**Comment by brooswit** [comment]
I reported this over on the Weapon Leveling github, and they report that if you use the latest forge then the bug doesn't occur: https://github.com/GeradesoLukas/weaponleveling/issues/17

**Comment by varHarrie** [comment]
Same issue with 1.18.2 Fabric: https://pastebin.com/MFJxkT1c

**Comment by ZsoltMolnarrr** [comment]
The issue can no longer be reproduced.
