### ISSUE TITLE
ScalaCube Forge Server Fails to Load Mod

### ISSUE THREAD

**Issue by JAMalcolmson** [ZsoltMolnarrr/BetterCombat#256]
**Minecraft version** - 1.19.2
**Mod loader** - Forge
**Mod version** - bettercombat-forge-1.7.1+1.19.jar
**I am using the latest version available** - Appears so

**Describe the bug**
From crash log:
-- MOD bettercombat --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.10.jar%23667!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.10.jar%23666!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /home/minecraft/server/mods/bettercombat-forge-1.7.1+1.19.jar
	Failure message: Better Combat (bettercombat) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.7.1+1.19
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.2.10.jar%2367!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
	at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.forName(Class.java:383) ~[?:?] {re:mixin}
	at java.lang.Class.forName(Class.java:376) ~[?:?] {re:mixin}
	at net.bettercombat.compatibility.CompatibilityFlags.doesClassExist(CompatibilityFlags.java:30) ~[bettercombat-forge-1.7.1+1.19.jar%23412!/:?] {re:classloading}
	at net.bettercombat.compatibility.CompatibilityFlags.initialize(CompatibilityFlags.java:15) ~[bettercombat-forge-1.7.1+1.19.jar%23412!/:?] {re:classloading}
	at net.bettercombat.BetterCombat.onInitialize(BetterCombat.java:38) ~[bettercombat-forge-1.7.1+1.19.jar%23412!/:?] {re:mixin,re:classloading}
	at net.bettercombat.forge.BetterCombatForge.<init>(BetterCombatForge.java:22) ~[bettercombat-forge-1.7.1+1.19.jar%23412!/:?] {re:classloading}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.10.jar%23667!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.10.jar%23666!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**To Reproduce**
Create ScalaCube Minecraft server for Minecraft 1.19.2, Forge version 43.2.10 (I actually need to use Forge 43.2.11 client-side, but that version of forge isn't available on ScalaCube yet. I suspect this may be relevant to the issue.)

**Expected behavior**
It loads the mod and launches.

**Screenshots or video recordings**
N/A

**Additional context**
N/A

**Comment by ZsoltMolnarrr** [comment]
Better Combat does not use any GUI, hence this crashlog doesn't seem like a valid issue of the mod itself.
Did you try the troubleshooting steps written on Discord?

**Comment by JAMalcolmson** [comment]
The issue was fixed while I was troubleshooting issues with other mods. 9 times out of 10 when I get a mod error, the crash log basically declares it has something to do with the main menu GUI, even if it has absolutely nothing to do with that, and I'm not really sure how to interpret it any better than to just ask the mod makers if they ave any suggestions.

**Comment by ZsoltMolnarrr** [comment]
The Discord trouble shooting guide recommends a few tips for Forge. Mainly to never use latest version of Forge, always use recommended version (recommended by Forge themselves).
Since I cannot reproduce this issue, the problem is either Forge version, or something specific to Scalacube.
