### ISSUE TITLE
Crash on version 1.20.4

### ISSUE THREAD

**Issue by ykvox** [ZsoltMolnarrr/BetterCombat#337]
1.20.4
Fabric
bettercombat-fabric-1.8.1+1.20.2
latest on 1.20.2

Attacking any entity with a weapon in hand will cause the came to crash
here is the report:

`Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_270 net.minecraft.class_1657.method_5781()'
	at net.bettercombat.logic.TargetHelper.getRelation(TargetHelper.java:40)
	at net.bettercombat.client.collision.TargetFinder.lambda$getInitialTargets$2(TargetFinder.java:99)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.bettercombat.client.collision.TargetFinder.getInitialTargets(TargetFinder.java:102)
	at net.bettercombat.client.collision.TargetFinder.findAttackTargetResult(TargetFinder.java:35)
	at net.bettercombat.client.collision.TargetFinder.findAttackTargets(TargetFinder.java:80)
	at net.minecraft.class_310.updateTargetsIfNeeded(class_310.java:6059)
	at net.minecraft.class_310.handler$zic000$bettercombat$pre_Tick(class_310.java:6078)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
`

i wish you a nice day !

**Comment by chefexperte** [comment]
Yeah, I am getting the exact same error in 1.8.4 for 1.20.1 when playing on 1.20.4

**Comment by ZsoltMolnarrr** [comment]
1.20.4 is not yet supported, this issue is simply invalid.

**Comment by ykvox** [comment]
you're completely right, my bad !
good luck on bringing this project to future versions :)
