### ISSUE TITLE
[1.21.1, Bug] The server with the mod is crashing

### ISSUE THREAD

**Issue by MagicalAlexey** [ZsoltMolnarrr/BetterCombat#411]
**Minecraft version** - 1.21.1
**Mod loader** - NeoForge
**Mod version** - 2.0.1
**I am using the latest version available** - yes

**Describe the bug**
The server with the mod is crashing

**To Reproduce**
1. Start server
2. See crush

**Expected behavior**
The server starts successfully with the mod

**Screenshots or video recordings**
![image](https://github.com/user-attachments/assets/08d3f365-2665-4ca8-8259-9350140d7ba8)

**Comment by MagicalAlexey** [comment]
`[02:03:11] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[02:03:14] [modloading-worker-0/ERROR] [ne.ne.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: bettercombat, class net.bettercombat.neoforge.NeoForgeMod
java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/serializer/PartitioningSerializer$GlobalData
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:196) ~[securejarhandler-3.0.8.jar:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?] {}
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at TRANSFORMER/bettercombat@2.0.1+1.21.1/net.bettercombat.BetterCombatMod.init(BetterCombatMod.java:31) ~[bettercombat-neoforge-2.0.1+1.21.1.jar%23127!/:?] {re:mixin,re:classloading}
        at TRANSFORMER/bettercombat@2.0.1+1.21.1/net.bettercombat.neoforge.NeoForgeMod.<init>(NeoForgeMod.java:15) ~[bettercombat-neoforge-2.0.1+1.21.1.jar%23127!/:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?] {}
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?] {}
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?] {}
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?] {}
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?] {}
Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.serializer.PartitioningSerializer$GlobalData
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216) ~[securejarhandler-3.0.8.jar:?] {}
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216) ~[securejarhandler-3.0.8.jar:?] {}
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        ... 24 more
[02:03:14] [modloading-worker-0/INFO] [ne.ne.ne.co.NeoForgeMod/NEOFORGE-MOD]: NeoForge mod loading, version 21.1.26, for MC 1.21.1
[02:03:14] [main/FATAL] [ne.ne.fm.ModLoader/LOADING]: Failed to wait for future Mod Construction, 1 errors found
[02:03:14] [main/FATAL] [ne.ne.ne.co.NeoForgeMod/]: Preparing crash report with UUID 0abddebe-e122-4326-94b8-27cdb42643cc
[02:03:14] [main/FATAL] [ne.ne.ne.se.lo.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2024-09-09_02.03.14-fml.txt
[02:03:14] [main/FATAL] [ne.ne.ne.co.NeoForgeMod/]: Preparing crash report with UUID 15402549-edff-43f1-a210-f0422cbcfd3e
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.
Time: 2024-09-09 02:03:14
Description: Mod loading error has occurred
java.lang.Exception: Mod Loading has failed
        at TRANSFORMER/neoforge@21.1.26/net.neoforged.neoforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:58) ~[neoforge-21.1.26-universal.jar%23126!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.26/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:41) ~[neoforge-21.1.26-universal.jar%23126!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21.1-20240808.144430-srg.jar%23125!/:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%2362!/:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: main
Stacktrace:
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD bettercombat --
Details:
        Caused by 0: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/serializer/PartitioningSerializer$GlobalData
                at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
                at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?] {}
                at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:196) ~[securejarhandler-3.0.8.jar:?] {}
                at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
                at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?] {}
                at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
                at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?] {}
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
                at TRANSFORMER/bettercombat@2.0.1+1.21.1/net.bettercombat.BetterCombatMod.init(BetterCombatMod.java:31) ~[bettercombat-neoforge-2.0.1+1.21.1.jar%23127!/:?] {re:mixin,re:classloading}
                at TRANSFORMER/bettercombat@2.0.1+1.21.1/net.bettercombat.neoforge.NeoForgeMod.<init>(NeoForgeMod.java:15) ~[bettercombat-neoforge-2.0.1+1.21.1.jar%23127!/:?] {re:classloading}
                at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
                at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
                at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
                at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.24.jar%2360!/:4.0] {}
                at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.24.jar%2360!/:4.0] {}
                at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.24.jar%2360!/:4.0] {}
                at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {}
                at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
                at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}
        Mod File: /home/container/mods/bettercombat-neoforge-2.0.1+1.21.1.jar
        Failure message: fml.modloadingissue.failedtoloadmod
        Mod Version: 2.0.1+1.21.1
        Mod Issue URL: NOT PROVIDED
        Exception message: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.serializer.PartitioningSerializer$GlobalData
Stacktrace:
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216) ~[securejarhandler-3.0.8.jar:?] {}
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216) ~[securejarhandler-3.0.8.jar:?] {}
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:196) ~[securejarhandler-3.0.8.jar:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?] {}
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at TRANSFORMER/bettercombat@2.0.1+1.21.1/net.bettercombat.BetterCombatMod.init(BetterCombatMod.java:31) ~[bettercombat-neoforge-2.0.1+1.21.1.jar%23127!/:?] {re:mixin,re:classloading}
        at TRANSFORMER/bettercombat@2.0.1+1.21.1/net.bettercombat.neoforge.NeoForgeMod.<init>(NeoForgeMod.java:15) ~[bettercombat-neoforge-2.0.1+1.21.1.jar%23127!/:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {}
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}
-- System Details --
Details:
        Minecraft Version: 1.21.1
        Minecraft Version ID: 1.21.1
        Operating System: Linux (amd64) version 6.1.0-13-amd64
        Java Version: 21.0.2, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
        Memory: 173971040 bytes (165 MiB) / 377847808 bytes (360 MiB) up to 4139646976 bytes (3947 MiB)
        CPUs: 4
        Processor Vendor: AuthenticAMD
        Processor Name: AMD Ryzen 9 7950X3D 16-Core Processor
        Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
        Microarchitecture: Zen 3
        Frequency (GHz): -0.00
        Number of physical packages: 1
        Number of physical CPUs: 16
        Number of logical CPUs: 32
        Graphics card #0 name: unknown
        Graphics card #0 vendor: unknown
        Graphics card #0 VRAM (MiB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: unknown
        Virtual memory max (MiB): 129189.20
        Virtual memory used (MiB): 163869.73
        Swap memory total (MiB): 32734.00
        Swap memory used (MiB): 12802.21
        Space in storage for jna.tmpdir (MiB): <path not set>
        Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
        Space in storage for io.netty.native.workdir (MiB): <path not set>
        Space in storage for java.io.tmpdir (MiB): available: 200.00, total: 200.00
        Space in storage for workdir (MiB): available: 1900509.75, total: 3569202.50
        JVM Flags: 5 total; -Xms128M -XX:MaxRAMPercentage=95.0 -XX:ConcGCThreads=4 -XX:ParallelGCThreads=4 -XX:+UseSerialGC
        ModLauncher: 11.0.4+main.d2e20e43
        ModLauncher launch target: forgeserver
        ModLauncher services: 
                sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE 
                loader-4.0.24.jar slf4jfixer PLUGINSERVICE 
                loader-4.0.24.jar runtime_enum_extender PLUGINSERVICE 
                at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
                loader-4.0.24.jar runtimedistcleaner PLUGINSERVICE 
                modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
                modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
        FML Language Providers: 
                javafml@4.0
                lowcodefml@4.0
                minecraft@4.0
        Mod List: 
                server-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: NOSIGNATURE
                Pehkui-3.8.3+1.21-neoforge.jar                    |Pehkui                        |pehkui                        |3.8.3+1.21-neoforge |Manifest: NOSIGNATURE
                geckolib-neoforge-1.21.1-4.6.3.jar                |GeckoLib 4                    |geckolib                      |4.6.3               |Manifest: NOSIGNATURE
                player-animation-lib-forge-2.0.0-alpha1+1.21.jar  |Player Animator               |playeranimator                |2.0.0-alpha1+1.21   |Manifest: NOSIGNATURE
                bettercombat-neoforge-2.0.1+1.21.1.jar            |Better Combat                 |bettercombat                  |2.0.1+1.21.1        |Manifest: NOSIGNATURE
                CustomSkinLoader_ForgeV3-14.20 (1).jar            |CustomSkinLoader              |customskinloader              |14.20               |Manifest: 4a:31:8b:cf:34:eb:d0:13:f3:19:39:d5:d2:b9:12:78:b5:f2:8d:91:3e:6f:8f:ed:97:48:00:69:e1:30:3a:54
                neoforge-21.1.26-universal.jar                    |NeoForge                      |neoforge                      |21.1.26             |Manifest: NOSIGNATURE
                cpapi-v15.jar                                     |Colorful Powers API           |cpapi                         |15                  |Manifest: NOSIGNATURE
                Keepers-of-the-Stones-II-1.0.0.41.jar             |Keepers of the Stones II      |power                         |1.0.0.41            |Manifest: NOSIGNATURE
        Crash Report UUID: 15402549-edff-43f1-a210-f0422cbcfd3e
        FML: 4.0.24
        NeoForge: 21.1.26
[02:03:14] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
        - Better Combat (bettercombat) has failed to load correctly
          java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/serializer/PartitioningSerializer$GlobalData
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:281) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.dispatchParallelTask(ModLoader.java:244) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.constructMods(ModLoader.java:152) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:142) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at TRANSFORMER/neoforge@21.1.26/net.neoforged.neoforge.internal.CommonModLoader.begin(CommonModLoader.java:49) ~[neoforge-21.1.26-universal.jar%23126!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.26/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:34) ~[neoforge-21.1.26-universal.jar%23126!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21.1-20240808.144430-srg.jar%23125!/:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.24.jar%2360!/:4.0] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%2362!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%2362!/:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}`

**Comment by MagicalAlexey** [comment]
[latest (3).log](https://github.com/user-attachments/files/16923939/latest.3.log)
